# Generated by Django 3.0.5 on 2020-04-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_mimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mimg',
            field=models.ImageField(upload_to='media/media'),
        ),
    ]
