# Generated by Django 3.0.5 on 2020-04-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200427_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mimg',
            field=models.ImageField(upload_to='media'),
        ),
    ]
